apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: todo-backend-config
  namespace: todo-backend
spec:
  healthCheck:
    type: HTTP
    requestPath: /actuator/health
    port: 5050
    checkIntervalSec: 30
    timeoutSec: 10
    healthyThreshold: 1
    unhealthyThreshold: 3
