apiVersion: v1
kind: Service
metadata:
  name: todo-backend-metrics
  namespace: todo-backend
  labels:
    app: todo-backend
    release: kube-prometheus   # IMPORTANT: Prometheus Operator looks for this
spec:
  selector:
    app: todo-backend
  ports:
    - name: metrics
      port: 5050
      targetPort: 5050
